### PR TITLE
Models

### PR DESCRIPTION
**Pull request by meganle**
Created models:
- Organization
- Course
- Lecture
- Question
- Response

Also added relationships to User model.

Current Schema:
clicker_db

### CODE REVIEW

**Comment by Jma353** [comment]
Is everyone on board with this data model?

**Comment by Jma353** [comment]
Also - this looks good as a basis for placing indices on specific fields and declaring formal foreign keys / triggers (like `ON DELETE CASCADE`), but we can always do that in a different PR.  Ran the branch locally and the models seemed to successfully generate all the tables.  

```
mysql> use clicker_db_dev;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+-----------------------------------+
| Tables_in_clicker_db_dev          |
+-----------------------------------+
| courses                           |
| lectures                          |
| organizations                     |
| questions                         |
| responses                         |
| sessions                          |
| users                             |
| users_admin_courses_courses_id    |
| users_enrolled_courses_courses_id |
+-----------------------------------+
```

Maybe include a screenshot of that success-state in the next PR related to data-model changes.  Other than that, so long as everyone is on board with this data model, this looks great!

**Comment by loganallen** [comment]
Make sure the Question has an answer/answers field

**Comment by meganle** [comment]
Yeah right now in the `Question` class there is a field named `data` that is a json containing choices, answers, etc to account for the different question types. For example, for a question with multiple answers `data` would be:
` {“choices”: [“A”, “B”, “C”, “D”], “answer”: [“A”, “C”]}`

**Pull request merged**
