### PR TITLE
Repos

### PR DESCRIPTION
**Pull request by meganle**
- Put default values for model fields to prevent fields from being read only

- Added repos for each model according to API docs

- Added pagination to repos

### CODE REVIEW

**Comment by mrkev** [comment]
LGTM

**Comment by Jma353** [comment]
Will look at this this evening

**Comment by Jma353** [comment]
Lol accidental closing

**Comment by dantheli** [comment]
LGTM

**Comment by mrkev** [comment]
this didn't get merged?

**Comment by meganle** [comment]
I merged from the command line following the appdev bible instructions. Not sure why it wasn't recognized 4a996f6379ecae39492ef088f6aa1d886f6a7034

**Comment by dantheli** [comment]
Okay we gotta change the Bible to just make it say merge

**Pull request closed without merging**
